syntax enable
colorscheme basic-dark
hi Normal guibg=NONE ctermbg=NONE

set tabstop=4 "Number of *visual* space when a tab is detected
set softtabstop=2 "Number of spaces replacing a tab
set expandtab "Replace the tab by the spaces

set mouse=a

set number "Show lines

set cursorline "Shows exactly at what column is displayeb the cursor

set wildmenu "Displays an autocompletion sidemenu

set showmatch "Highlights machting [({

highlight OverLength ctermbg=red guibg=red
match OverLength /\%82v.\+/

highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/

