# Asbolute PATH to the dotfiles directory.
export DOTFILES_ROOT="${ZDOTDIR:-$HOME}/Dev/dotfiles"

# Ensures that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

